version: '3.5'

services:
  pgdb:
    container_name: postgres
    restart: always
    build:
      context: .
      dockerfile: DockerfilePg
    environment:
        POSTGRES_PASSWORD: 123456789
    ports:
       - '5432:5432'

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5433:80'