version: '3.5'

services:
  pgdb:
    container_name: postgres
    restart: always
    build:
      context: .
      dockerfile: DockerfilePg
    environment:
        POSTGRES_PASSWORD: 123456789
    ports:
       - '5432:5432'
  zipkin:
   image: openzipkin/zipkin
   container_name: zipkin
   restart: always
   ports:
      - '9411:9411'